AllCops:
  TargetRubyVersion: '2.3'

Metrics/BlockLength:
  Exclude:
    - 'stock_shaker.gemspec'

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 140

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 20

# The guiding principle of classes is SRP, SRP can't be accurately measured by LoC
Metrics/ClassLength:
  Max: 1500

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
#Style/StringLiterals:
#  EnforcedStyle: double_quotes

# Frozen string literals may be default in Ruby 3.0. Default Enabled: true
# See more: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment
FrozenStringLiteralComment:
  Enabled: true

# Style/ClassAndModuleChildren:
#  EnforcedStyle: compact

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Disabled warning DateTime
Style/DateTime:
  Enabled: false

# Disabled Style/Documentation
Style/Documentation:
  Enabled: false

# Disabled เพื่อคอมเม้นภาษาไทยด้ายยยยยยยย
Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 20